version: 2
updates:
  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "ci"
      include: "scope"
    reviewers:
      - "suryabulusu"
    assignees:
      - "suryabulusu"
    labels:
      - "dependencies"
      - "github-actions"
    
  # npm updates (if you later add package.json)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"  
      time: "09:00"
    commit-message:
      prefix: "deps"
      include: "scope"
    reviewers:
      - "suryabulusu"
    assignees:
      - "suryabulusu"
    labels:
      - "dependencies"
      - "javascript"
    ignore:
      # Ignore major version updates for now
      - dependency-name: "*"
        update-types: ["version-update:semver-major"] 