name: Lint and Format Check

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run ESLint
        run: npm run lint:js
        
      - name: Run Stylelint
        run: npm run lint:css
        
      - name: Run HTML validation
        run: npm run lint:html
        
      - name: Check Prettier formatting
        run: |
          npm run format
          if ! git diff --exit-code; then
            echo "❌ Code is not properly formatted!"
            echo "Run 'npm run format' to fix formatting issues."
            exit 1
          else
            echo "✅ Code is properly formatted!"
          fi 